language: go
go:
  - 1.7.x
  - 1.8.x
sudo: false
install:
  - go get -v github.com/Masterminds/glide
  - glide install
  - go install
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
