/* Users */
ALTER TABLE `Users` CHANGE `UserId` `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT, CHANGE `Email` `email` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `Username` `username` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `Password` `password` MEDIUMBLOB NULL DEFAULT NULL, CHANGE `MultiSigAddress` `multi_sig_address` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `MultiSigScript` `multi_sig_script` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `PoolPubKeyAddr` `pool_publey_address` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `UserPubKeyAddr` `user_publey_address` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `UserFeeAddr` `user_fee_address` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `HeightRegistered` `height_registered` BIGINT(20) NULL DEFAULT NULL, CHANGE `EmailVerified` `email_verified` BIGINT(20) NULL DEFAULT NULL, CHANGE `EmailToken` `email_token` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `APIToken` `api_token` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL;
RENAME `Users` to `users`;

/* PasswordReset */
ALTER TABLE `PasswordReset` CHANGE `PasswordResetID` `password_reset_id` BIGINT(20) NOT NULL AUTO_INCREMENT, CHANGE `UserId` `user_id` BIGINT(20) NULL DEFAULT NULL, CHANGE `Token` `token` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `Created` `created` BIGINT(20) NULL DEFAULT NULL, CHANGE `Expires` `expires` BIGINT(20) NULL DEFAULT NULL;
RENAME `PasswordReset` to `password_reset`;

/* EmailChange */
ALTER TABLE `EmailChange` CHANGE `EmailChangeID` `email_change_id` BIGINT(20) NOT NULL AUTO_INCREMENT, CHANGE `UserId` `user_id` BIGINT(20) NULL DEFAULT NULL, CHANGE `NewEmail` `new_email` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `Token` `token` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL, CHANGE `Created` `created` BIGINT(20) NULL DEFAULT NULL, CHANGE `Expires` `expires` BIGINT(20) NULL DEFAULT NULL;
RENAME `EmailChange` to `email_change`;
