// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package stakepoolrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAddedLowFeeTicketsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddedLowFeeTicketsRequest) Reset()         { *m = GetAddedLowFeeTicketsRequest{} }
func (m *GetAddedLowFeeTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAddedLowFeeTicketsRequest) ProtoMessage()    {}
func (*GetAddedLowFeeTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *GetAddedLowFeeTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddedLowFeeTicketsRequest.Unmarshal(m, b)
}
func (m *GetAddedLowFeeTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddedLowFeeTicketsRequest.Marshal(b, m, deterministic)
}
func (m *GetAddedLowFeeTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddedLowFeeTicketsRequest.Merge(m, src)
}
func (m *GetAddedLowFeeTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAddedLowFeeTicketsRequest.Size(m)
}
func (m *GetAddedLowFeeTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddedLowFeeTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddedLowFeeTicketsRequest proto.InternalMessageInfo

type GetAddedLowFeeTicketsResponse struct {
	Tickets              []*Ticket `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAddedLowFeeTicketsResponse) Reset()         { *m = GetAddedLowFeeTicketsResponse{} }
func (m *GetAddedLowFeeTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAddedLowFeeTicketsResponse) ProtoMessage()    {}
func (*GetAddedLowFeeTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *GetAddedLowFeeTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddedLowFeeTicketsResponse.Unmarshal(m, b)
}
func (m *GetAddedLowFeeTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddedLowFeeTicketsResponse.Marshal(b, m, deterministic)
}
func (m *GetAddedLowFeeTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddedLowFeeTicketsResponse.Merge(m, src)
}
func (m *GetAddedLowFeeTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAddedLowFeeTicketsResponse.Size(m)
}
func (m *GetAddedLowFeeTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddedLowFeeTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddedLowFeeTicketsResponse proto.InternalMessageInfo

func (m *GetAddedLowFeeTicketsResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

type GetIgnoredLowFeeTicketsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIgnoredLowFeeTicketsRequest) Reset()         { *m = GetIgnoredLowFeeTicketsRequest{} }
func (m *GetIgnoredLowFeeTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*GetIgnoredLowFeeTicketsRequest) ProtoMessage()    {}
func (*GetIgnoredLowFeeTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *GetIgnoredLowFeeTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIgnoredLowFeeTicketsRequest.Unmarshal(m, b)
}
func (m *GetIgnoredLowFeeTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIgnoredLowFeeTicketsRequest.Marshal(b, m, deterministic)
}
func (m *GetIgnoredLowFeeTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIgnoredLowFeeTicketsRequest.Merge(m, src)
}
func (m *GetIgnoredLowFeeTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_GetIgnoredLowFeeTicketsRequest.Size(m)
}
func (m *GetIgnoredLowFeeTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIgnoredLowFeeTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIgnoredLowFeeTicketsRequest proto.InternalMessageInfo

type GetIgnoredLowFeeTicketsResponse struct {
	Tickets              []*Ticket `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetIgnoredLowFeeTicketsResponse) Reset()         { *m = GetIgnoredLowFeeTicketsResponse{} }
func (m *GetIgnoredLowFeeTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*GetIgnoredLowFeeTicketsResponse) ProtoMessage()    {}
func (*GetIgnoredLowFeeTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GetIgnoredLowFeeTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIgnoredLowFeeTicketsResponse.Unmarshal(m, b)
}
func (m *GetIgnoredLowFeeTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIgnoredLowFeeTicketsResponse.Marshal(b, m, deterministic)
}
func (m *GetIgnoredLowFeeTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIgnoredLowFeeTicketsResponse.Merge(m, src)
}
func (m *GetIgnoredLowFeeTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_GetIgnoredLowFeeTicketsResponse.Size(m)
}
func (m *GetIgnoredLowFeeTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIgnoredLowFeeTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIgnoredLowFeeTicketsResponse proto.InternalMessageInfo

func (m *GetIgnoredLowFeeTicketsResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

type GetLiveTicketsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLiveTicketsRequest) Reset()         { *m = GetLiveTicketsRequest{} }
func (m *GetLiveTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLiveTicketsRequest) ProtoMessage()    {}
func (*GetLiveTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetLiveTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLiveTicketsRequest.Unmarshal(m, b)
}
func (m *GetLiveTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLiveTicketsRequest.Marshal(b, m, deterministic)
}
func (m *GetLiveTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLiveTicketsRequest.Merge(m, src)
}
func (m *GetLiveTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLiveTicketsRequest.Size(m)
}
func (m *GetLiveTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLiveTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLiveTicketsRequest proto.InternalMessageInfo

type GetLiveTicketsResponse struct {
	Tickets              []*Ticket `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetLiveTicketsResponse) Reset()         { *m = GetLiveTicketsResponse{} }
func (m *GetLiveTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLiveTicketsResponse) ProtoMessage()    {}
func (*GetLiveTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *GetLiveTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLiveTicketsResponse.Unmarshal(m, b)
}
func (m *GetLiveTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLiveTicketsResponse.Marshal(b, m, deterministic)
}
func (m *GetLiveTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLiveTicketsResponse.Merge(m, src)
}
func (m *GetLiveTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_GetLiveTicketsResponse.Size(m)
}
func (m *GetLiveTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLiveTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLiveTicketsResponse proto.InternalMessageInfo

func (m *GetLiveTicketsResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

type SetAddedLowFeeTicketsRequest struct {
	Tickets              []*Ticket `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetAddedLowFeeTicketsRequest) Reset()         { *m = SetAddedLowFeeTicketsRequest{} }
func (m *SetAddedLowFeeTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*SetAddedLowFeeTicketsRequest) ProtoMessage()    {}
func (*SetAddedLowFeeTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *SetAddedLowFeeTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAddedLowFeeTicketsRequest.Unmarshal(m, b)
}
func (m *SetAddedLowFeeTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAddedLowFeeTicketsRequest.Marshal(b, m, deterministic)
}
func (m *SetAddedLowFeeTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAddedLowFeeTicketsRequest.Merge(m, src)
}
func (m *SetAddedLowFeeTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_SetAddedLowFeeTicketsRequest.Size(m)
}
func (m *SetAddedLowFeeTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAddedLowFeeTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAddedLowFeeTicketsRequest proto.InternalMessageInfo

func (m *SetAddedLowFeeTicketsRequest) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

type SetAddedLowFeeTicketsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAddedLowFeeTicketsResponse) Reset()         { *m = SetAddedLowFeeTicketsResponse{} }
func (m *SetAddedLowFeeTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*SetAddedLowFeeTicketsResponse) ProtoMessage()    {}
func (*SetAddedLowFeeTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *SetAddedLowFeeTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAddedLowFeeTicketsResponse.Unmarshal(m, b)
}
func (m *SetAddedLowFeeTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAddedLowFeeTicketsResponse.Marshal(b, m, deterministic)
}
func (m *SetAddedLowFeeTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAddedLowFeeTicketsResponse.Merge(m, src)
}
func (m *SetAddedLowFeeTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_SetAddedLowFeeTicketsResponse.Size(m)
}
func (m *SetAddedLowFeeTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAddedLowFeeTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAddedLowFeeTicketsResponse proto.InternalMessageInfo

type SetUserVotingPrefsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserVotingPrefsResponse) Reset()         { *m = SetUserVotingPrefsResponse{} }
func (m *SetUserVotingPrefsResponse) String() string { return proto.CompactTextString(m) }
func (*SetUserVotingPrefsResponse) ProtoMessage()    {}
func (*SetUserVotingPrefsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *SetUserVotingPrefsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserVotingPrefsResponse.Unmarshal(m, b)
}
func (m *SetUserVotingPrefsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserVotingPrefsResponse.Marshal(b, m, deterministic)
}
func (m *SetUserVotingPrefsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserVotingPrefsResponse.Merge(m, src)
}
func (m *SetUserVotingPrefsResponse) XXX_Size() int {
	return xxx_messageInfo_SetUserVotingPrefsResponse.Size(m)
}
func (m *SetUserVotingPrefsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserVotingPrefsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserVotingPrefsResponse proto.InternalMessageInfo

type SetUserVotingPrefsRequest struct {
	UserVotingConfig     []*UserVotingConfigEntry `protobuf:"bytes,1,rep,name=user_voting_config,json=userVotingConfig,proto3" json:"user_voting_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SetUserVotingPrefsRequest) Reset()         { *m = SetUserVotingPrefsRequest{} }
func (m *SetUserVotingPrefsRequest) String() string { return proto.CompactTextString(m) }
func (*SetUserVotingPrefsRequest) ProtoMessage()    {}
func (*SetUserVotingPrefsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *SetUserVotingPrefsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserVotingPrefsRequest.Unmarshal(m, b)
}
func (m *SetUserVotingPrefsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserVotingPrefsRequest.Marshal(b, m, deterministic)
}
func (m *SetUserVotingPrefsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserVotingPrefsRequest.Merge(m, src)
}
func (m *SetUserVotingPrefsRequest) XXX_Size() int {
	return xxx_messageInfo_SetUserVotingPrefsRequest.Size(m)
}
func (m *SetUserVotingPrefsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserVotingPrefsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserVotingPrefsRequest proto.InternalMessageInfo

func (m *SetUserVotingPrefsRequest) GetUserVotingConfig() []*UserVotingConfigEntry {
	if m != nil {
		return m.UserVotingConfig
	}
	return nil
}

type AddMissingTicketRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMissingTicketRequest) Reset()         { *m = AddMissingTicketRequest{} }
func (m *AddMissingTicketRequest) String() string { return proto.CompactTextString(m) }
func (*AddMissingTicketRequest) ProtoMessage()    {}
func (*AddMissingTicketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *AddMissingTicketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMissingTicketRequest.Unmarshal(m, b)
}
func (m *AddMissingTicketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMissingTicketRequest.Marshal(b, m, deterministic)
}
func (m *AddMissingTicketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMissingTicketRequest.Merge(m, src)
}
func (m *AddMissingTicketRequest) XXX_Size() int {
	return xxx_messageInfo_AddMissingTicketRequest.Size(m)
}
func (m *AddMissingTicketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMissingTicketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMissingTicketRequest proto.InternalMessageInfo

func (m *AddMissingTicketRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type AddMissingTicketResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMissingTicketResponse) Reset()         { *m = AddMissingTicketResponse{} }
func (m *AddMissingTicketResponse) String() string { return proto.CompactTextString(m) }
func (*AddMissingTicketResponse) ProtoMessage()    {}
func (*AddMissingTicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *AddMissingTicketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMissingTicketResponse.Unmarshal(m, b)
}
func (m *AddMissingTicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMissingTicketResponse.Marshal(b, m, deterministic)
}
func (m *AddMissingTicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMissingTicketResponse.Merge(m, src)
}
func (m *AddMissingTicketResponse) XXX_Size() int {
	return xxx_messageInfo_AddMissingTicketResponse.Size(m)
}
func (m *AddMissingTicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMissingTicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMissingTicketResponse proto.InternalMessageInfo

type GetTicketsRequest struct {
	IncludeImmature      bool     `protobuf:"varint,1,opt,name=IncludeImmature,proto3" json:"IncludeImmature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTicketsRequest) Reset()         { *m = GetTicketsRequest{} }
func (m *GetTicketsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTicketsRequest) ProtoMessage()    {}
func (*GetTicketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *GetTicketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicketsRequest.Unmarshal(m, b)
}
func (m *GetTicketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicketsRequest.Marshal(b, m, deterministic)
}
func (m *GetTicketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicketsRequest.Merge(m, src)
}
func (m *GetTicketsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTicketsRequest.Size(m)
}
func (m *GetTicketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicketsRequest proto.InternalMessageInfo

func (m *GetTicketsRequest) GetIncludeImmature() bool {
	if m != nil {
		return m.IncludeImmature
	}
	return false
}

type GetTicketsResponse struct {
	Tickets              [][]byte `protobuf:"bytes,1,rep,name=Tickets,proto3" json:"Tickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTicketsResponse) Reset()         { *m = GetTicketsResponse{} }
func (m *GetTicketsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTicketsResponse) ProtoMessage()    {}
func (*GetTicketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *GetTicketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicketsResponse.Unmarshal(m, b)
}
func (m *GetTicketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicketsResponse.Marshal(b, m, deterministic)
}
func (m *GetTicketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicketsResponse.Merge(m, src)
}
func (m *GetTicketsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTicketsResponse.Size(m)
}
func (m *GetTicketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicketsResponse proto.InternalMessageInfo

func (m *GetTicketsResponse) GetTickets() [][]byte {
	if m != nil {
		return m.Tickets
	}
	return nil
}

type ListScriptsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListScriptsRequest) Reset()         { *m = ListScriptsRequest{} }
func (m *ListScriptsRequest) String() string { return proto.CompactTextString(m) }
func (*ListScriptsRequest) ProtoMessage()    {}
func (*ListScriptsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *ListScriptsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListScriptsRequest.Unmarshal(m, b)
}
func (m *ListScriptsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListScriptsRequest.Marshal(b, m, deterministic)
}
func (m *ListScriptsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListScriptsRequest.Merge(m, src)
}
func (m *ListScriptsRequest) XXX_Size() int {
	return xxx_messageInfo_ListScriptsRequest.Size(m)
}
func (m *ListScriptsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListScriptsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListScriptsRequest proto.InternalMessageInfo

type ListScriptsResponse struct {
	Scripts              [][]byte `protobuf:"bytes,1,rep,name=Scripts,proto3" json:"Scripts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListScriptsResponse) Reset()         { *m = ListScriptsResponse{} }
func (m *ListScriptsResponse) String() string { return proto.CompactTextString(m) }
func (*ListScriptsResponse) ProtoMessage()    {}
func (*ListScriptsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *ListScriptsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListScriptsResponse.Unmarshal(m, b)
}
func (m *ListScriptsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListScriptsResponse.Marshal(b, m, deterministic)
}
func (m *ListScriptsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListScriptsResponse.Merge(m, src)
}
func (m *ListScriptsResponse) XXX_Size() int {
	return xxx_messageInfo_ListScriptsResponse.Size(m)
}
func (m *ListScriptsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListScriptsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListScriptsResponse proto.InternalMessageInfo

func (m *ListScriptsResponse) GetScripts() [][]byte {
	if m != nil {
		return m.Scripts
	}
	return nil
}

type AccountSyncAddressIndexRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Branch               uint32   `protobuf:"varint,2,opt,name=Branch,proto3" json:"Branch,omitempty"`
	Index                int64    `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountSyncAddressIndexRequest) Reset()         { *m = AccountSyncAddressIndexRequest{} }
func (m *AccountSyncAddressIndexRequest) String() string { return proto.CompactTextString(m) }
func (*AccountSyncAddressIndexRequest) ProtoMessage()    {}
func (*AccountSyncAddressIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *AccountSyncAddressIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSyncAddressIndexRequest.Unmarshal(m, b)
}
func (m *AccountSyncAddressIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSyncAddressIndexRequest.Marshal(b, m, deterministic)
}
func (m *AccountSyncAddressIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSyncAddressIndexRequest.Merge(m, src)
}
func (m *AccountSyncAddressIndexRequest) XXX_Size() int {
	return xxx_messageInfo_AccountSyncAddressIndexRequest.Size(m)
}
func (m *AccountSyncAddressIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSyncAddressIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSyncAddressIndexRequest proto.InternalMessageInfo

func (m *AccountSyncAddressIndexRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AccountSyncAddressIndexRequest) GetBranch() uint32 {
	if m != nil {
		return m.Branch
	}
	return 0
}

func (m *AccountSyncAddressIndexRequest) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type AccountSyncAddressIndexResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountSyncAddressIndexResponse) Reset()         { *m = AccountSyncAddressIndexResponse{} }
func (m *AccountSyncAddressIndexResponse) String() string { return proto.CompactTextString(m) }
func (*AccountSyncAddressIndexResponse) ProtoMessage()    {}
func (*AccountSyncAddressIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *AccountSyncAddressIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSyncAddressIndexResponse.Unmarshal(m, b)
}
func (m *AccountSyncAddressIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSyncAddressIndexResponse.Marshal(b, m, deterministic)
}
func (m *AccountSyncAddressIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSyncAddressIndexResponse.Merge(m, src)
}
func (m *AccountSyncAddressIndexResponse) XXX_Size() int {
	return xxx_messageInfo_AccountSyncAddressIndexResponse.Size(m)
}
func (m *AccountSyncAddressIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSyncAddressIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSyncAddressIndexResponse proto.InternalMessageInfo

type ImportScriptRequest struct {
	Script               []byte   `protobuf:"bytes,1,opt,name=Script,proto3" json:"Script,omitempty"`
	Rescan               bool     `protobuf:"varint,2,opt,name=Rescan,proto3" json:"Rescan,omitempty"`
	RescanHeight         int64    `protobuf:"varint,3,opt,name=RescanHeight,proto3" json:"RescanHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportScriptRequest) Reset()         { *m = ImportScriptRequest{} }
func (m *ImportScriptRequest) String() string { return proto.CompactTextString(m) }
func (*ImportScriptRequest) ProtoMessage()    {}
func (*ImportScriptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *ImportScriptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportScriptRequest.Unmarshal(m, b)
}
func (m *ImportScriptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportScriptRequest.Marshal(b, m, deterministic)
}
func (m *ImportScriptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportScriptRequest.Merge(m, src)
}
func (m *ImportScriptRequest) XXX_Size() int {
	return xxx_messageInfo_ImportScriptRequest.Size(m)
}
func (m *ImportScriptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportScriptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportScriptRequest proto.InternalMessageInfo

func (m *ImportScriptRequest) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *ImportScriptRequest) GetRescan() bool {
	if m != nil {
		return m.Rescan
	}
	return false
}

func (m *ImportScriptRequest) GetRescanHeight() int64 {
	if m != nil {
		return m.RescanHeight
	}
	return 0
}

type ImportScriptResponse struct {
	HeightImported       int64    `protobuf:"varint,1,opt,name=HeightImported,proto3" json:"HeightImported,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportScriptResponse) Reset()         { *m = ImportScriptResponse{} }
func (m *ImportScriptResponse) String() string { return proto.CompactTextString(m) }
func (*ImportScriptResponse) ProtoMessage()    {}
func (*ImportScriptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *ImportScriptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportScriptResponse.Unmarshal(m, b)
}
func (m *ImportScriptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportScriptResponse.Marshal(b, m, deterministic)
}
func (m *ImportScriptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportScriptResponse.Merge(m, src)
}
func (m *ImportScriptResponse) XXX_Size() int {
	return xxx_messageInfo_ImportScriptResponse.Size(m)
}
func (m *ImportScriptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportScriptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportScriptResponse proto.InternalMessageInfo

func (m *ImportScriptResponse) GetHeightImported() int64 {
	if m != nil {
		return m.HeightImported
	}
	return 0
}

type StakePoolUserInfoRequest struct {
	MultiSigAddress      string   `protobuf:"bytes,1,opt,name=MultiSigAddress,proto3" json:"MultiSigAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakePoolUserInfoRequest) Reset()         { *m = StakePoolUserInfoRequest{} }
func (m *StakePoolUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*StakePoolUserInfoRequest) ProtoMessage()    {}
func (*StakePoolUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *StakePoolUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakePoolUserInfoRequest.Unmarshal(m, b)
}
func (m *StakePoolUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakePoolUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *StakePoolUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakePoolUserInfoRequest.Merge(m, src)
}
func (m *StakePoolUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_StakePoolUserInfoRequest.Size(m)
}
func (m *StakePoolUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StakePoolUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StakePoolUserInfoRequest proto.InternalMessageInfo

func (m *StakePoolUserInfoRequest) GetMultiSigAddress() string {
	if m != nil {
		return m.MultiSigAddress
	}
	return ""
}

type StakePoolUserInfoResponse struct {
	Tickets              []*StakePoolUserTicket `protobuf:"bytes,1,rep,name=Tickets,proto3" json:"Tickets,omitempty"`
	InvalidTickets       []string               `protobuf:"bytes,2,rep,name=InvalidTickets,proto3" json:"InvalidTickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StakePoolUserInfoResponse) Reset()         { *m = StakePoolUserInfoResponse{} }
func (m *StakePoolUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*StakePoolUserInfoResponse) ProtoMessage()    {}
func (*StakePoolUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *StakePoolUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakePoolUserInfoResponse.Unmarshal(m, b)
}
func (m *StakePoolUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakePoolUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *StakePoolUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakePoolUserInfoResponse.Merge(m, src)
}
func (m *StakePoolUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_StakePoolUserInfoResponse.Size(m)
}
func (m *StakePoolUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StakePoolUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StakePoolUserInfoResponse proto.InternalMessageInfo

func (m *StakePoolUserInfoResponse) GetTickets() []*StakePoolUserTicket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

func (m *StakePoolUserInfoResponse) GetInvalidTickets() []string {
	if m != nil {
		return m.InvalidTickets
	}
	return nil
}

type WalletInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletInfoRequest) Reset()         { *m = WalletInfoRequest{} }
func (m *WalletInfoRequest) String() string { return proto.CompactTextString(m) }
func (*WalletInfoRequest) ProtoMessage()    {}
func (*WalletInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *WalletInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletInfoRequest.Unmarshal(m, b)
}
func (m *WalletInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletInfoRequest.Marshal(b, m, deterministic)
}
func (m *WalletInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletInfoRequest.Merge(m, src)
}
func (m *WalletInfoRequest) XXX_Size() int {
	return xxx_messageInfo_WalletInfoRequest.Size(m)
}
func (m *WalletInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WalletInfoRequest proto.InternalMessageInfo

type WalletInfoResponse struct {
	VoteVersion          uint32   `protobuf:"varint,1,opt,name=VoteVersion,proto3" json:"VoteVersion,omitempty"`
	DaemonConnected      bool     `protobuf:"varint,2,opt,name=DaemonConnected,proto3" json:"DaemonConnected,omitempty"`
	Unlocked             bool     `protobuf:"varint,3,opt,name=Unlocked,proto3" json:"Unlocked,omitempty"`
	Voting               bool     `protobuf:"varint,4,opt,name=Voting,proto3" json:"Voting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletInfoResponse) Reset()         { *m = WalletInfoResponse{} }
func (m *WalletInfoResponse) String() string { return proto.CompactTextString(m) }
func (*WalletInfoResponse) ProtoMessage()    {}
func (*WalletInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *WalletInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletInfoResponse.Unmarshal(m, b)
}
func (m *WalletInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletInfoResponse.Marshal(b, m, deterministic)
}
func (m *WalletInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletInfoResponse.Merge(m, src)
}
func (m *WalletInfoResponse) XXX_Size() int {
	return xxx_messageInfo_WalletInfoResponse.Size(m)
}
func (m *WalletInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WalletInfoResponse proto.InternalMessageInfo

func (m *WalletInfoResponse) GetVoteVersion() uint32 {
	if m != nil {
		return m.VoteVersion
	}
	return 0
}

func (m *WalletInfoResponse) GetDaemonConnected() bool {
	if m != nil {
		return m.DaemonConnected
	}
	return false
}

func (m *WalletInfoResponse) GetUnlocked() bool {
	if m != nil {
		return m.Unlocked
	}
	return false
}

func (m *WalletInfoResponse) GetVoting() bool {
	if m != nil {
		return m.Voting
	}
	return false
}

type ValidateAddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAddressRequest) Reset()         { *m = ValidateAddressRequest{} }
func (m *ValidateAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateAddressRequest) ProtoMessage()    {}
func (*ValidateAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}

func (m *ValidateAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAddressRequest.Unmarshal(m, b)
}
func (m *ValidateAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAddressRequest.Marshal(b, m, deterministic)
}
func (m *ValidateAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAddressRequest.Merge(m, src)
}
func (m *ValidateAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateAddressRequest.Size(m)
}
func (m *ValidateAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAddressRequest proto.InternalMessageInfo

func (m *ValidateAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ValidateAddressResponse struct {
	IsMine               bool     `protobuf:"varint,1,opt,name=IsMine,proto3" json:"IsMine,omitempty"`
	PubKeyAddr           string   `protobuf:"bytes,2,opt,name=PubKeyAddr,proto3" json:"PubKeyAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAddressResponse) Reset()         { *m = ValidateAddressResponse{} }
func (m *ValidateAddressResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateAddressResponse) ProtoMessage()    {}
func (*ValidateAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}

func (m *ValidateAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAddressResponse.Unmarshal(m, b)
}
func (m *ValidateAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAddressResponse.Marshal(b, m, deterministic)
}
func (m *ValidateAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAddressResponse.Merge(m, src)
}
func (m *ValidateAddressResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateAddressResponse.Size(m)
}
func (m *ValidateAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAddressResponse proto.InternalMessageInfo

func (m *ValidateAddressResponse) GetIsMine() bool {
	if m != nil {
		return m.IsMine
	}
	return false
}

func (m *ValidateAddressResponse) GetPubKeyAddr() string {
	if m != nil {
		return m.PubKeyAddr
	}
	return ""
}

type CreateMultisigRequest struct {
	Address              []string `protobuf:"bytes,1,rep,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMultisigRequest) Reset()         { *m = CreateMultisigRequest{} }
func (m *CreateMultisigRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMultisigRequest) ProtoMessage()    {}
func (*CreateMultisigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{26}
}

func (m *CreateMultisigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMultisigRequest.Unmarshal(m, b)
}
func (m *CreateMultisigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMultisigRequest.Marshal(b, m, deterministic)
}
func (m *CreateMultisigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMultisigRequest.Merge(m, src)
}
func (m *CreateMultisigRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMultisigRequest.Size(m)
}
func (m *CreateMultisigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMultisigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMultisigRequest proto.InternalMessageInfo

func (m *CreateMultisigRequest) GetAddress() []string {
	if m != nil {
		return m.Address
	}
	return nil
}

type CreateMultisigResponse struct {
	RedeemScript         string   `protobuf:"bytes,1,opt,name=RedeemScript,proto3" json:"RedeemScript,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMultisigResponse) Reset()         { *m = CreateMultisigResponse{} }
func (m *CreateMultisigResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMultisigResponse) ProtoMessage()    {}
func (*CreateMultisigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{27}
}

func (m *CreateMultisigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMultisigResponse.Unmarshal(m, b)
}
func (m *CreateMultisigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMultisigResponse.Marshal(b, m, deterministic)
}
func (m *CreateMultisigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMultisigResponse.Merge(m, src)
}
func (m *CreateMultisigResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMultisigResponse.Size(m)
}
func (m *CreateMultisigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMultisigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMultisigResponse proto.InternalMessageInfo

func (m *CreateMultisigResponse) GetRedeemScript() string {
	if m != nil {
		return m.RedeemScript
	}
	return ""
}

func (m *CreateMultisigResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type StakePoolUserTicket struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Ticket               string   `protobuf:"bytes,2,opt,name=Ticket,proto3" json:"Ticket,omitempty"`
	TicketHeight         uint32   `protobuf:"varint,3,opt,name=TicketHeight,proto3" json:"TicketHeight,omitempty"`
	SpentBy              string   `protobuf:"bytes,4,opt,name=SpentBy,proto3" json:"SpentBy,omitempty"`
	SpentByHeight        uint32   `protobuf:"varint,5,opt,name=SpentByHeight,proto3" json:"SpentByHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakePoolUserTicket) Reset()         { *m = StakePoolUserTicket{} }
func (m *StakePoolUserTicket) String() string { return proto.CompactTextString(m) }
func (*StakePoolUserTicket) ProtoMessage()    {}
func (*StakePoolUserTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{28}
}

func (m *StakePoolUserTicket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakePoolUserTicket.Unmarshal(m, b)
}
func (m *StakePoolUserTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakePoolUserTicket.Marshal(b, m, deterministic)
}
func (m *StakePoolUserTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakePoolUserTicket.Merge(m, src)
}
func (m *StakePoolUserTicket) XXX_Size() int {
	return xxx_messageInfo_StakePoolUserTicket.Size(m)
}
func (m *StakePoolUserTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_StakePoolUserTicket.DiscardUnknown(m)
}

var xxx_messageInfo_StakePoolUserTicket proto.InternalMessageInfo

func (m *StakePoolUserTicket) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StakePoolUserTicket) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *StakePoolUserTicket) GetTicketHeight() uint32 {
	if m != nil {
		return m.TicketHeight
	}
	return 0
}

func (m *StakePoolUserTicket) GetSpentBy() string {
	if m != nil {
		return m.SpentBy
	}
	return ""
}

func (m *StakePoolUserTicket) GetSpentByHeight() uint32 {
	if m != nil {
		return m.SpentByHeight
	}
	return 0
}

type Ticket struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{29}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Ticket) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type UserVotingConfigEntry struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	MultiSigAddress      string   `protobuf:"bytes,2,opt,name=MultiSigAddress,proto3" json:"MultiSigAddress,omitempty"`
	VoteBits             int64    `protobuf:"varint,3,opt,name=VoteBits,proto3" json:"VoteBits,omitempty"`
	VoteBitsVersion      int64    `protobuf:"varint,4,opt,name=VoteBitsVersion,proto3" json:"VoteBitsVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserVotingConfigEntry) Reset()         { *m = UserVotingConfigEntry{} }
func (m *UserVotingConfigEntry) String() string { return proto.CompactTextString(m) }
func (*UserVotingConfigEntry) ProtoMessage()    {}
func (*UserVotingConfigEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{30}
}

func (m *UserVotingConfigEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserVotingConfigEntry.Unmarshal(m, b)
}
func (m *UserVotingConfigEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserVotingConfigEntry.Marshal(b, m, deterministic)
}
func (m *UserVotingConfigEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserVotingConfigEntry.Merge(m, src)
}
func (m *UserVotingConfigEntry) XXX_Size() int {
	return xxx_messageInfo_UserVotingConfigEntry.Size(m)
}
func (m *UserVotingConfigEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_UserVotingConfigEntry.DiscardUnknown(m)
}

var xxx_messageInfo_UserVotingConfigEntry proto.InternalMessageInfo

func (m *UserVotingConfigEntry) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserVotingConfigEntry) GetMultiSigAddress() string {
	if m != nil {
		return m.MultiSigAddress
	}
	return ""
}

func (m *UserVotingConfigEntry) GetVoteBits() int64 {
	if m != nil {
		return m.VoteBits
	}
	return 0
}

func (m *UserVotingConfigEntry) GetVoteBitsVersion() int64 {
	if m != nil {
		return m.VoteBitsVersion
	}
	return 0
}

type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{31}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

type VersionResponse struct {
	VersionString        string   `protobuf:"bytes,1,opt,name=version_string,json=versionString,proto3" json:"version_string,omitempty"`
	Major                uint32   `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor                uint32   `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch                uint32   `protobuf:"varint,4,opt,name=patch,proto3" json:"patch,omitempty"`
	Prerelease           string   `protobuf:"bytes,5,opt,name=prerelease,proto3" json:"prerelease,omitempty"`
	BuildMetadata        string   `protobuf:"bytes,6,opt,name=build_metadata,json=buildMetadata,proto3" json:"build_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{32}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersionString() string {
	if m != nil {
		return m.VersionString
	}
	return ""
}

func (m *VersionResponse) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *VersionResponse) GetMinor() uint32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *VersionResponse) GetPatch() uint32 {
	if m != nil {
		return m.Patch
	}
	return 0
}

func (m *VersionResponse) GetPrerelease() string {
	if m != nil {
		return m.Prerelease
	}
	return ""
}

func (m *VersionResponse) GetBuildMetadata() string {
	if m != nil {
		return m.BuildMetadata
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAddedLowFeeTicketsRequest)(nil), "stakepoolrpc.GetAddedLowFeeTicketsRequest")
	proto.RegisterType((*GetAddedLowFeeTicketsResponse)(nil), "stakepoolrpc.GetAddedLowFeeTicketsResponse")
	proto.RegisterType((*GetIgnoredLowFeeTicketsRequest)(nil), "stakepoolrpc.GetIgnoredLowFeeTicketsRequest")
	proto.RegisterType((*GetIgnoredLowFeeTicketsResponse)(nil), "stakepoolrpc.GetIgnoredLowFeeTicketsResponse")
	proto.RegisterType((*GetLiveTicketsRequest)(nil), "stakepoolrpc.GetLiveTicketsRequest")
	proto.RegisterType((*GetLiveTicketsResponse)(nil), "stakepoolrpc.GetLiveTicketsResponse")
	proto.RegisterType((*SetAddedLowFeeTicketsRequest)(nil), "stakepoolrpc.SetAddedLowFeeTicketsRequest")
	proto.RegisterType((*SetAddedLowFeeTicketsResponse)(nil), "stakepoolrpc.SetAddedLowFeeTicketsResponse")
	proto.RegisterType((*SetUserVotingPrefsResponse)(nil), "stakepoolrpc.SetUserVotingPrefsResponse")
	proto.RegisterType((*SetUserVotingPrefsRequest)(nil), "stakepoolrpc.SetUserVotingPrefsRequest")
	proto.RegisterType((*AddMissingTicketRequest)(nil), "stakepoolrpc.AddMissingTicketRequest")
	proto.RegisterType((*AddMissingTicketResponse)(nil), "stakepoolrpc.AddMissingTicketResponse")
	proto.RegisterType((*GetTicketsRequest)(nil), "stakepoolrpc.GetTicketsRequest")
	proto.RegisterType((*GetTicketsResponse)(nil), "stakepoolrpc.GetTicketsResponse")
	proto.RegisterType((*ListScriptsRequest)(nil), "stakepoolrpc.ListScriptsRequest")
	proto.RegisterType((*ListScriptsResponse)(nil), "stakepoolrpc.ListScriptsResponse")
	proto.RegisterType((*AccountSyncAddressIndexRequest)(nil), "stakepoolrpc.AccountSyncAddressIndexRequest")
	proto.RegisterType((*AccountSyncAddressIndexResponse)(nil), "stakepoolrpc.AccountSyncAddressIndexResponse")
	proto.RegisterType((*ImportScriptRequest)(nil), "stakepoolrpc.ImportScriptRequest")
	proto.RegisterType((*ImportScriptResponse)(nil), "stakepoolrpc.ImportScriptResponse")
	proto.RegisterType((*StakePoolUserInfoRequest)(nil), "stakepoolrpc.StakePoolUserInfoRequest")
	proto.RegisterType((*StakePoolUserInfoResponse)(nil), "stakepoolrpc.StakePoolUserInfoResponse")
	proto.RegisterType((*WalletInfoRequest)(nil), "stakepoolrpc.WalletInfoRequest")
	proto.RegisterType((*WalletInfoResponse)(nil), "stakepoolrpc.WalletInfoResponse")
	proto.RegisterType((*ValidateAddressRequest)(nil), "stakepoolrpc.ValidateAddressRequest")
	proto.RegisterType((*ValidateAddressResponse)(nil), "stakepoolrpc.ValidateAddressResponse")
	proto.RegisterType((*CreateMultisigRequest)(nil), "stakepoolrpc.CreateMultisigRequest")
	proto.RegisterType((*CreateMultisigResponse)(nil), "stakepoolrpc.CreateMultisigResponse")
	proto.RegisterType((*StakePoolUserTicket)(nil), "stakepoolrpc.StakePoolUserTicket")
	proto.RegisterType((*Ticket)(nil), "stakepoolrpc.Ticket")
	proto.RegisterType((*UserVotingConfigEntry)(nil), "stakepoolrpc.UserVotingConfigEntry")
	proto.RegisterType((*VersionRequest)(nil), "stakepoolrpc.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "stakepoolrpc.VersionResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x5f, 0x4f, 0xe3, 0x46,
	0x10, 0x57, 0xc8, 0x1d, 0x90, 0x81, 0xf0, 0x67, 0x81, 0x90, 0xb3, 0xf8, 0x13, 0x7c, 0x77, 0x5c,
	0xd4, 0xf6, 0xa8, 0x4a, 0xa5, 0xbe, 0x54, 0xad, 0x04, 0x5c, 0x0f, 0xa2, 0x42, 0x0f, 0xd6, 0x07,
	0xad, 0x54, 0xa9, 0xc8, 0xd8, 0x43, 0x70, 0x49, 0xd6, 0xae, 0xbd, 0x49, 0xcb, 0xdb, 0x7d, 0x88,
	0xbe, 0xf7, 0xb9, 0x1f, 0xa3, 0xdf, 0xac, 0xf2, 0x7a, 0x4c, 0xec, 0x8d, 0x13, 0xb8, 0x7b, 0xf3,
	0xfc, 0x76, 0x76, 0xfe, 0xef, 0xcc, 0x18, 0x2a, 0x76, 0xe0, 0xed, 0x04, 0xa1, 0x2f, 0x7d, 0x36,
	0x1b, 0x49, 0xfb, 0x16, 0x03, 0xdf, 0xef, 0x84, 0x81, 0x63, 0x6e, 0xc0, 0xda, 0x21, 0xca, 0x3d,
	0xd7, 0x45, 0xf7, 0xd8, 0xff, 0xf3, 0x2d, 0xe2, 0x7b, 0xcf, 0xb9, 0x45, 0x19, 0x71, 0xfc, 0xa3,
	0x87, 0x91, 0x34, 0xdf, 0xc1, 0xfa, 0x88, 0xf3, 0x28, 0xf0, 0x45, 0x84, 0x6c, 0x07, 0xa6, 0x64,
	0x02, 0xd5, 0x4b, 0x8d, 0x72, 0x73, 0x66, 0x77, 0x79, 0x27, 0xab, 0x60, 0x27, 0xe1, 0xe7, 0x29,
	0x93, 0xd9, 0x80, 0x8d, 0x43, 0x94, 0xad, 0xb6, 0xf0, 0xc3, 0x11, 0x2a, 0xcf, 0x60, 0x73, 0x24,
	0xc7, 0x27, 0x2a, 0x5d, 0x85, 0x95, 0x43, 0x94, 0xc7, 0x5e, 0x5f, 0xd7, 0x75, 0x04, 0x35, 0xfd,
	0xe0, 0x13, 0x55, 0xfc, 0x04, 0x6b, 0xd6, 0x98, 0x40, 0x7e, 0xb4, 0xbc, 0x4d, 0x58, 0xb7, 0xc6,
	0x05, 0xde, 0x5c, 0x03, 0xc3, 0x42, 0x79, 0x1e, 0x61, 0x78, 0xe1, 0x4b, 0x4f, 0xb4, 0x4f, 0x43,
	0xbc, 0x1e, 0x9c, 0x0a, 0x78, 0x56, 0x74, 0x9a, 0xd8, 0x72, 0x06, 0xac, 0x17, 0x61, 0x78, 0xd9,
	0x57, 0x47, 0x97, 0x8e, 0x2f, 0xae, 0xbd, 0x36, 0x99, 0xf5, 0x3c, 0x6f, 0xd6, 0x40, 0xc2, 0x81,
	0xe2, 0xfa, 0x41, 0xc8, 0xf0, 0x8e, 0x2f, 0xf4, 0x34, 0xd8, 0x7c, 0x0d, 0xab, 0x7b, 0xae, 0x7b,
	0xe2, 0x45, 0x91, 0x27, 0xda, 0xe4, 0x0b, 0x69, 0x63, 0xf0, 0xe4, 0xc8, 0x8e, 0x6e, 0xea, 0xa5,
	0x46, 0xa9, 0x39, 0xcb, 0xd5, 0xb7, 0x69, 0x40, 0x7d, 0x98, 0x9d, 0x4c, 0xff, 0x0e, 0x16, 0x0f,
	0x51, 0x6a, 0xe1, 0x6b, 0xc2, 0x7c, 0x4b, 0x38, 0x9d, 0x9e, 0x8b, 0xad, 0x6e, 0xd7, 0x96, 0xbd,
	0x10, 0x95, 0xbc, 0x69, 0xae, 0xc3, 0xe6, 0x0e, 0xb0, 0xec, 0x75, 0x4a, 0x67, 0x1d, 0xa6, 0xde,
	0x67, 0xc2, 0x3f, 0xcb, 0x53, 0xd2, 0x5c, 0x06, 0x76, 0xec, 0x45, 0xd2, 0x72, 0x42, 0x2f, 0x18,
	0x14, 0xc6, 0x97, 0xb0, 0x94, 0x43, 0x07, 0x62, 0x08, 0x4a, 0xc5, 0x10, 0x69, 0xde, 0xc0, 0xc6,
	0x9e, 0xe3, 0xf8, 0x3d, 0x21, 0xad, 0x3b, 0xe1, 0xec, 0xb9, 0x6e, 0x88, 0x51, 0xd4, 0x12, 0x2e,
	0xfe, 0x95, 0xba, 0x50, 0x87, 0x29, 0xe2, 0x50, 0xa6, 0x57, 0x78, 0x4a, 0xb2, 0x1a, 0x4c, 0xee,
	0x87, 0xb6, 0x70, 0x6e, 0xea, 0x13, 0x8d, 0x52, 0xb3, 0xca, 0x89, 0x62, 0xcb, 0xf0, 0x54, 0x49,
	0xa8, 0x97, 0x1b, 0xa5, 0x66, 0x99, 0x27, 0x84, 0xb9, 0x05, 0x9b, 0x23, 0x35, 0x51, 0x08, 0x3d,
	0x58, 0x6a, 0x75, 0x03, 0x3f, 0x24, 0xfb, 0x53, 0x0b, 0x6a, 0x30, 0x99, 0x00, 0x94, 0x0b, 0xa2,
	0x62, 0x9c, 0x63, 0xe4, 0xd8, 0x42, 0xe9, 0x9f, 0xe6, 0x44, 0x31, 0x13, 0x66, 0x93, 0xaf, 0x23,
	0xf4, 0xda, 0x37, 0x92, 0xcc, 0xc8, 0x61, 0xe6, 0xf7, 0xb0, 0x9c, 0x57, 0x45, 0x91, 0xda, 0x86,
	0xb9, 0x84, 0x23, 0x39, 0x45, 0x57, 0xe9, 0x2c, 0x73, 0x0d, 0x35, 0xdf, 0x40, 0xdd, 0x8a, 0x0b,
	0xee, 0xd4, 0xf7, 0x3b, 0x71, 0xb1, 0xb5, 0xc4, 0xb5, 0x9f, 0x49, 0xfa, 0x49, 0xaf, 0x23, 0x3d,
	0xcb, 0x6b, 0x93, 0x9b, 0x14, 0x39, 0x1d, 0x36, 0x3f, 0x94, 0xe0, 0x59, 0x81, 0x18, 0xb2, 0xe5,
	0xdb, 0x7c, 0xf2, 0x67, 0x76, 0xb7, 0xf2, 0x45, 0x9e, 0xbb, 0x99, 0x3e, 0x44, 0xba, 0x11, 0x3b,
	0xd2, 0x12, 0x7d, 0xbb, 0xe3, 0xb9, 0xa9, 0x8c, 0x89, 0x46, 0xb9, 0x59, 0xe1, 0x1a, 0x6a, 0x2e,
	0xc1, 0xe2, 0xcf, 0x76, 0xa7, 0x83, 0x32, 0xe3, 0x81, 0xf9, 0x77, 0x09, 0x58, 0x16, 0x25, 0x83,
	0x1a, 0x30, 0x73, 0xe1, 0x4b, 0xbc, 0xc0, 0x30, 0xf2, 0x7c, 0xa1, 0x9c, 0xaa, 0xf2, 0x2c, 0x14,
	0xbb, 0xfe, 0xc6, 0xc6, 0xae, 0x2f, 0x0e, 0x7c, 0x21, 0xd0, 0x89, 0xe3, 0x97, 0xe4, 0x46, 0x87,
	0x99, 0x01, 0xd3, 0xe7, 0xa2, 0xe3, 0x3b, 0xb7, 0xe8, 0xaa, 0x04, 0x4d, 0xf3, 0x7b, 0x3a, 0x4e,
	0x6c, 0xf2, 0x4a, 0xeb, 0x4f, 0x92, 0xc4, 0x26, 0x94, 0xb9, 0x0b, 0xb5, 0x8b, 0xd8, 0x76, 0x5b,
	0x22, 0x45, 0x30, 0x5b, 0xa4, 0xb9, 0x50, 0xa7, 0xa4, 0x79, 0x06, 0xab, 0x43, 0x77, 0xc8, 0x9d,
	0x1a, 0x4c, 0xb6, 0xa2, 0x13, 0x4f, 0xa4, 0x6f, 0x92, 0x28, 0xb6, 0x01, 0x70, 0xda, 0xbb, 0xfa,
	0x11, 0xef, 0xe2, 0x0b, 0xca, 0xfe, 0x0a, 0xcf, 0x20, 0xe6, 0x57, 0xb0, 0x72, 0x10, 0xa2, 0x2d,
	0x51, 0xa5, 0x33, 0xf2, 0xda, 0x85, 0x56, 0x94, 0xb3, 0x56, 0x5c, 0x40, 0x4d, 0xbf, 0x42, 0x46,
	0xa8, 0x62, 0x75, 0x11, 0xbb, 0x99, 0x12, 0xaf, 0xf0, 0x1c, 0x96, 0x95, 0x3b, 0x91, 0xf7, 0xee,
	0xdf, 0x12, 0x2c, 0x15, 0x94, 0x81, 0x7a, 0x32, 0xd2, 0x96, 0xbd, 0x34, 0x1c, 0x44, 0xc5, 0x78,
	0xc2, 0x41, 0x82, 0x88, 0x8a, 0xad, 0x48, 0xbe, 0x32, 0x4f, 0xa6, 0xca, 0x73, 0x98, 0x6a, 0x22,
	0x01, 0x0a, 0xb9, 0x7f, 0xa7, 0xd2, 0x52, 0xe1, 0x29, 0xc9, 0x5e, 0x40, 0x95, 0x3e, 0xe9, 0xfa,
	0x53, 0x75, 0x3d, 0x0f, 0x9a, 0xdf, 0xa4, 0xba, 0x47, 0x67, 0xeb, 0xbe, 0xe9, 0x4e, 0x64, 0x9a,
	0xee, 0x3f, 0x25, 0x58, 0x29, 0xec, 0xe7, 0xb1, 0x37, 0xea, 0xd1, 0xa4, 0x8f, 0x94, 0xa8, 0xa2,
	0x07, 0x38, 0x51, 0xf8, 0x00, 0xe3, 0x2a, 0x8c, 0xcb, 0x77, 0xdf, 0x93, 0x11, 0xb5, 0x89, 0x7b,
	0x3a, 0x96, 0x92, 0x7e, 0xa7, 0x15, 0xff, 0x44, 0xb1, 0xe8, 0xb0, 0xb9, 0x00, 0x73, 0xf4, 0x99,
	0x3e, 0xa0, 0xff, 0x4a, 0x30, 0x7f, 0x0f, 0x51, 0xa6, 0x5f, 0xc2, 0x5c, 0x3f, 0x81, 0x2e, 0x23,
	0x19, 0xc6, 0xd5, 0x9d, 0x38, 0x5f, 0x25, 0xd4, 0x52, 0x60, 0xdc, 0x3d, 0xbb, 0xf6, 0xef, 0x7e,
	0x48, 0x4d, 0x35, 0x21, 0x14, 0xea, 0x09, 0x3f, 0xa4, 0xcc, 0x24, 0x44, 0x8c, 0x06, 0xb6, 0x74,
	0x6e, 0x94, 0x61, 0x55, 0x9e, 0x10, 0x71, 0xfd, 0x06, 0x21, 0x86, 0xd8, 0x41, 0x3b, 0x42, 0x95,
	0x8b, 0x0a, 0xcf, 0x20, 0xb1, 0x21, 0x57, 0x3d, 0xaf, 0xe3, 0x5e, 0x76, 0x51, 0xda, 0xae, 0x2d,
	0xed, 0xfa, 0x64, 0x62, 0x88, 0x42, 0x4f, 0x08, 0xdc, 0xfd, 0x30, 0x03, 0x8b, 0x56, 0xda, 0x6f,
	0x5c, 0x0b, 0xc3, 0xbe, 0xe7, 0x20, 0x0b, 0xd4, 0x4e, 0x32, 0x3c, 0xe0, 0xd9, 0x67, 0xf9, 0xe6,
	0x34, 0x6e, 0x3d, 0x33, 0x3e, 0x7f, 0x14, 0x2f, 0xc5, 0xad, 0x0f, 0xab, 0x23, 0x16, 0x2b, 0xf6,
	0xc5, 0x90, 0x9c, 0x31, 0x1b, 0x9a, 0xf1, 0xfa, 0x91, 0xdc, 0xa4, 0xf7, 0x57, 0x98, 0xcb, 0x2f,
	0x59, 0xec, 0xf9, 0x90, 0x80, 0xe1, 0xdd, 0xcc, 0x78, 0x31, 0x9e, 0x89, 0x84, 0x07, 0xb0, 0x62,
	0x3d, 0x26, 0x8c, 0xd6, 0x47, 0x84, 0x71, 0xec, 0xe2, 0xc5, 0xda, 0xc0, 0x86, 0x57, 0x2b, 0xf6,
	0x6a, 0x48, 0x44, 0xf1, 0xf2, 0x65, 0x34, 0x1f, 0x66, 0x24, 0x45, 0xe7, 0x30, 0x9b, 0x1d, 0xad,
	0x4c, 0x9b, 0x5a, 0x05, 0x13, 0xde, 0x30, 0xc7, 0xb1, 0x90, 0x58, 0x97, 0xaa, 0x31, 0x3b, 0x2a,
	0xd9, 0xf6, 0x98, 0x89, 0x98, 0x19, 0x68, 0xc6, 0xab, 0x07, 0xf9, 0x48, 0xcb, 0x3b, 0x80, 0xc1,
	0xe0, 0x63, 0x9b, 0xf9, 0x6b, 0x43, 0x83, 0xd2, 0x68, 0x8c, 0x66, 0x20, 0x81, 0xbf, 0xc1, 0xbc,
	0x36, 0x7f, 0x98, 0x56, 0x21, 0xc5, 0x23, 0xcd, 0x78, 0xf9, 0x00, 0x17, 0xc9, 0xb7, 0x61, 0x41,
	0x5f, 0x49, 0x99, 0x76, 0x75, 0xc4, 0x86, 0x6b, 0x6c, 0x3f, 0xc4, 0x36, 0x88, 0xc9, 0x60, 0x35,
	0xd5, 0x63, 0x32, 0xb4, 0xf3, 0xea, 0x31, 0x29, 0xd8, 0x6a, 0x39, 0xcc, 0x64, 0xb6, 0x54, 0xa6,
	0x5d, 0x18, 0x5e, 0x6b, 0x8d, 0xad, 0x31, 0x1c, 0x83, 0x2e, 0x31, 0x62, 0xbd, 0xd4, 0xbb, 0xc4,
	0xf8, 0x7d, 0x57, 0xef, 0x12, 0x0f, 0xec, 0xac, 0x71, 0x97, 0xc8, 0x4f, 0x76, 0xbd, 0x4b, 0x14,
	0xae, 0x0a, 0x7a, 0x97, 0x28, 0x5e, 0x0e, 0x76, 0x7f, 0xb9, 0x1f, 0x2c, 0x69, 0xfb, 0x7d, 0x0b,
	0x53, 0xe9, 0xae, 0xb5, 0xa6, 0x15, 0x48, 0x6e, 0x02, 0x19, 0xeb, 0x23, 0x4e, 0x13, 0xc9, 0x57,
	0x93, 0xea, 0xaf, 0xfa, 0xeb, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xac, 0x53, 0x7e, 0x8c, 0x62,
	0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StakepooldServiceClient is the client API for StakepooldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StakepooldServiceClient interface {
	GetAddedLowFeeTickets(ctx context.Context, in *GetAddedLowFeeTicketsRequest, opts ...grpc.CallOption) (*GetAddedLowFeeTicketsResponse, error)
	GetIgnoredLowFeeTickets(ctx context.Context, in *GetIgnoredLowFeeTicketsRequest, opts ...grpc.CallOption) (*GetIgnoredLowFeeTicketsResponse, error)
	GetLiveTickets(ctx context.Context, in *GetLiveTicketsRequest, opts ...grpc.CallOption) (*GetLiveTicketsResponse, error)
	SetAddedLowFeeTickets(ctx context.Context, in *SetAddedLowFeeTicketsRequest, opts ...grpc.CallOption) (*SetAddedLowFeeTicketsResponse, error)
	SetUserVotingPrefs(ctx context.Context, in *SetUserVotingPrefsRequest, opts ...grpc.CallOption) (*SetUserVotingPrefsResponse, error)
	ImportScript(ctx context.Context, in *ImportScriptRequest, opts ...grpc.CallOption) (*ImportScriptResponse, error)
	StakePoolUserInfo(ctx context.Context, in *StakePoolUserInfoRequest, opts ...grpc.CallOption) (*StakePoolUserInfoResponse, error)
	WalletInfo(ctx context.Context, in *WalletInfoRequest, opts ...grpc.CallOption) (*WalletInfoResponse, error)
	ValidateAddress(ctx context.Context, in *ValidateAddressRequest, opts ...grpc.CallOption) (*ValidateAddressResponse, error)
	AddMissingTicket(ctx context.Context, in *AddMissingTicketRequest, opts ...grpc.CallOption) (*AddMissingTicketResponse, error)
	GetTickets(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*GetTicketsResponse, error)
	ListScripts(ctx context.Context, in *ListScriptsRequest, opts ...grpc.CallOption) (*ListScriptsResponse, error)
	AccountSyncAddressIndex(ctx context.Context, in *AccountSyncAddressIndexRequest, opts ...grpc.CallOption) (*AccountSyncAddressIndexResponse, error)
	CreateMultisig(ctx context.Context, in *CreateMultisigRequest, opts ...grpc.CallOption) (*CreateMultisigResponse, error)
}

type stakepooldServiceClient struct {
	cc *grpc.ClientConn
}

func NewStakepooldServiceClient(cc *grpc.ClientConn) StakepooldServiceClient {
	return &stakepooldServiceClient{cc}
}

func (c *stakepooldServiceClient) GetAddedLowFeeTickets(ctx context.Context, in *GetAddedLowFeeTicketsRequest, opts ...grpc.CallOption) (*GetAddedLowFeeTicketsResponse, error) {
	out := new(GetAddedLowFeeTicketsResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/GetAddedLowFeeTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) GetIgnoredLowFeeTickets(ctx context.Context, in *GetIgnoredLowFeeTicketsRequest, opts ...grpc.CallOption) (*GetIgnoredLowFeeTicketsResponse, error) {
	out := new(GetIgnoredLowFeeTicketsResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/GetIgnoredLowFeeTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) GetLiveTickets(ctx context.Context, in *GetLiveTicketsRequest, opts ...grpc.CallOption) (*GetLiveTicketsResponse, error) {
	out := new(GetLiveTicketsResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/GetLiveTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) SetAddedLowFeeTickets(ctx context.Context, in *SetAddedLowFeeTicketsRequest, opts ...grpc.CallOption) (*SetAddedLowFeeTicketsResponse, error) {
	out := new(SetAddedLowFeeTicketsResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/SetAddedLowFeeTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) SetUserVotingPrefs(ctx context.Context, in *SetUserVotingPrefsRequest, opts ...grpc.CallOption) (*SetUserVotingPrefsResponse, error) {
	out := new(SetUserVotingPrefsResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/SetUserVotingPrefs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) ImportScript(ctx context.Context, in *ImportScriptRequest, opts ...grpc.CallOption) (*ImportScriptResponse, error) {
	out := new(ImportScriptResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/ImportScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) StakePoolUserInfo(ctx context.Context, in *StakePoolUserInfoRequest, opts ...grpc.CallOption) (*StakePoolUserInfoResponse, error) {
	out := new(StakePoolUserInfoResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/StakePoolUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) WalletInfo(ctx context.Context, in *WalletInfoRequest, opts ...grpc.CallOption) (*WalletInfoResponse, error) {
	out := new(WalletInfoResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/WalletInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) ValidateAddress(ctx context.Context, in *ValidateAddressRequest, opts ...grpc.CallOption) (*ValidateAddressResponse, error) {
	out := new(ValidateAddressResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/ValidateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) AddMissingTicket(ctx context.Context, in *AddMissingTicketRequest, opts ...grpc.CallOption) (*AddMissingTicketResponse, error) {
	out := new(AddMissingTicketResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/AddMissingTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) GetTickets(ctx context.Context, in *GetTicketsRequest, opts ...grpc.CallOption) (*GetTicketsResponse, error) {
	out := new(GetTicketsResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/GetTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) ListScripts(ctx context.Context, in *ListScriptsRequest, opts ...grpc.CallOption) (*ListScriptsResponse, error) {
	out := new(ListScriptsResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/ListScripts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) AccountSyncAddressIndex(ctx context.Context, in *AccountSyncAddressIndexRequest, opts ...grpc.CallOption) (*AccountSyncAddressIndexResponse, error) {
	out := new(AccountSyncAddressIndexResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/AccountSyncAddressIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakepooldServiceClient) CreateMultisig(ctx context.Context, in *CreateMultisigRequest, opts ...grpc.CallOption) (*CreateMultisigResponse, error) {
	out := new(CreateMultisigResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.StakepooldService/CreateMultisig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StakepooldServiceServer is the server API for StakepooldService service.
type StakepooldServiceServer interface {
	GetAddedLowFeeTickets(context.Context, *GetAddedLowFeeTicketsRequest) (*GetAddedLowFeeTicketsResponse, error)
	GetIgnoredLowFeeTickets(context.Context, *GetIgnoredLowFeeTicketsRequest) (*GetIgnoredLowFeeTicketsResponse, error)
	GetLiveTickets(context.Context, *GetLiveTicketsRequest) (*GetLiveTicketsResponse, error)
	SetAddedLowFeeTickets(context.Context, *SetAddedLowFeeTicketsRequest) (*SetAddedLowFeeTicketsResponse, error)
	SetUserVotingPrefs(context.Context, *SetUserVotingPrefsRequest) (*SetUserVotingPrefsResponse, error)
	ImportScript(context.Context, *ImportScriptRequest) (*ImportScriptResponse, error)
	StakePoolUserInfo(context.Context, *StakePoolUserInfoRequest) (*StakePoolUserInfoResponse, error)
	WalletInfo(context.Context, *WalletInfoRequest) (*WalletInfoResponse, error)
	ValidateAddress(context.Context, *ValidateAddressRequest) (*ValidateAddressResponse, error)
	AddMissingTicket(context.Context, *AddMissingTicketRequest) (*AddMissingTicketResponse, error)
	GetTickets(context.Context, *GetTicketsRequest) (*GetTicketsResponse, error)
	ListScripts(context.Context, *ListScriptsRequest) (*ListScriptsResponse, error)
	AccountSyncAddressIndex(context.Context, *AccountSyncAddressIndexRequest) (*AccountSyncAddressIndexResponse, error)
	CreateMultisig(context.Context, *CreateMultisigRequest) (*CreateMultisigResponse, error)
}

// UnimplementedStakepooldServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStakepooldServiceServer struct {
}

func (*UnimplementedStakepooldServiceServer) GetAddedLowFeeTickets(ctx context.Context, req *GetAddedLowFeeTicketsRequest) (*GetAddedLowFeeTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddedLowFeeTickets not implemented")
}
func (*UnimplementedStakepooldServiceServer) GetIgnoredLowFeeTickets(ctx context.Context, req *GetIgnoredLowFeeTicketsRequest) (*GetIgnoredLowFeeTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIgnoredLowFeeTickets not implemented")
}
func (*UnimplementedStakepooldServiceServer) GetLiveTickets(ctx context.Context, req *GetLiveTicketsRequest) (*GetLiveTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveTickets not implemented")
}
func (*UnimplementedStakepooldServiceServer) SetAddedLowFeeTickets(ctx context.Context, req *SetAddedLowFeeTicketsRequest) (*SetAddedLowFeeTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAddedLowFeeTickets not implemented")
}
func (*UnimplementedStakepooldServiceServer) SetUserVotingPrefs(ctx context.Context, req *SetUserVotingPrefsRequest) (*SetUserVotingPrefsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserVotingPrefs not implemented")
}
func (*UnimplementedStakepooldServiceServer) ImportScript(ctx context.Context, req *ImportScriptRequest) (*ImportScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportScript not implemented")
}
func (*UnimplementedStakepooldServiceServer) StakePoolUserInfo(ctx context.Context, req *StakePoolUserInfoRequest) (*StakePoolUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StakePoolUserInfo not implemented")
}
func (*UnimplementedStakepooldServiceServer) WalletInfo(ctx context.Context, req *WalletInfoRequest) (*WalletInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletInfo not implemented")
}
func (*UnimplementedStakepooldServiceServer) ValidateAddress(ctx context.Context, req *ValidateAddressRequest) (*ValidateAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAddress not implemented")
}
func (*UnimplementedStakepooldServiceServer) AddMissingTicket(ctx context.Context, req *AddMissingTicketRequest) (*AddMissingTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMissingTicket not implemented")
}
func (*UnimplementedStakepooldServiceServer) GetTickets(ctx context.Context, req *GetTicketsRequest) (*GetTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTickets not implemented")
}
func (*UnimplementedStakepooldServiceServer) ListScripts(ctx context.Context, req *ListScriptsRequest) (*ListScriptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScripts not implemented")
}
func (*UnimplementedStakepooldServiceServer) AccountSyncAddressIndex(ctx context.Context, req *AccountSyncAddressIndexRequest) (*AccountSyncAddressIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountSyncAddressIndex not implemented")
}
func (*UnimplementedStakepooldServiceServer) CreateMultisig(ctx context.Context, req *CreateMultisigRequest) (*CreateMultisigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMultisig not implemented")
}

func RegisterStakepooldServiceServer(s *grpc.Server, srv StakepooldServiceServer) {
	s.RegisterService(&_StakepooldService_serviceDesc, srv)
}

func _StakepooldService_GetAddedLowFeeTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddedLowFeeTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).GetAddedLowFeeTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/GetAddedLowFeeTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).GetAddedLowFeeTickets(ctx, req.(*GetAddedLowFeeTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_GetIgnoredLowFeeTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIgnoredLowFeeTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).GetIgnoredLowFeeTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/GetIgnoredLowFeeTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).GetIgnoredLowFeeTickets(ctx, req.(*GetIgnoredLowFeeTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_GetLiveTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).GetLiveTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/GetLiveTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).GetLiveTickets(ctx, req.(*GetLiveTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_SetAddedLowFeeTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAddedLowFeeTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).SetAddedLowFeeTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/SetAddedLowFeeTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).SetAddedLowFeeTickets(ctx, req.(*SetAddedLowFeeTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_SetUserVotingPrefs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserVotingPrefsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).SetUserVotingPrefs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/SetUserVotingPrefs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).SetUserVotingPrefs(ctx, req.(*SetUserVotingPrefsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_ImportScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).ImportScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/ImportScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).ImportScript(ctx, req.(*ImportScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_StakePoolUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StakePoolUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).StakePoolUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/StakePoolUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).StakePoolUserInfo(ctx, req.(*StakePoolUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_WalletInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).WalletInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/WalletInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).WalletInfo(ctx, req.(*WalletInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_ValidateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).ValidateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/ValidateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).ValidateAddress(ctx, req.(*ValidateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_AddMissingTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMissingTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).AddMissingTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/AddMissingTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).AddMissingTicket(ctx, req.(*AddMissingTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_GetTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).GetTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/GetTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).GetTickets(ctx, req.(*GetTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_ListScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).ListScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/ListScripts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).ListScripts(ctx, req.(*ListScriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_AccountSyncAddressIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountSyncAddressIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).AccountSyncAddressIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/AccountSyncAddressIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).AccountSyncAddressIndex(ctx, req.(*AccountSyncAddressIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakepooldService_CreateMultisig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMultisigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakepooldServiceServer).CreateMultisig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.StakepooldService/CreateMultisig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakepooldServiceServer).CreateMultisig(ctx, req.(*CreateMultisigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StakepooldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stakepoolrpc.StakepooldService",
	HandlerType: (*StakepooldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddedLowFeeTickets",
			Handler:    _StakepooldService_GetAddedLowFeeTickets_Handler,
		},
		{
			MethodName: "GetIgnoredLowFeeTickets",
			Handler:    _StakepooldService_GetIgnoredLowFeeTickets_Handler,
		},
		{
			MethodName: "GetLiveTickets",
			Handler:    _StakepooldService_GetLiveTickets_Handler,
		},
		{
			MethodName: "SetAddedLowFeeTickets",
			Handler:    _StakepooldService_SetAddedLowFeeTickets_Handler,
		},
		{
			MethodName: "SetUserVotingPrefs",
			Handler:    _StakepooldService_SetUserVotingPrefs_Handler,
		},
		{
			MethodName: "ImportScript",
			Handler:    _StakepooldService_ImportScript_Handler,
		},
		{
			MethodName: "StakePoolUserInfo",
			Handler:    _StakepooldService_StakePoolUserInfo_Handler,
		},
		{
			MethodName: "WalletInfo",
			Handler:    _StakepooldService_WalletInfo_Handler,
		},
		{
			MethodName: "ValidateAddress",
			Handler:    _StakepooldService_ValidateAddress_Handler,
		},
		{
			MethodName: "AddMissingTicket",
			Handler:    _StakepooldService_AddMissingTicket_Handler,
		},
		{
			MethodName: "GetTickets",
			Handler:    _StakepooldService_GetTickets_Handler,
		},
		{
			MethodName: "ListScripts",
			Handler:    _StakepooldService_ListScripts_Handler,
		},
		{
			MethodName: "AccountSyncAddressIndex",
			Handler:    _StakepooldService_AccountSyncAddressIndex_Handler,
		},
		{
			MethodName: "CreateMultisig",
			Handler:    _StakepooldService_CreateMultisig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// VersionServiceClient is the client API for VersionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VersionServiceClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type versionServiceClient struct {
	cc *grpc.ClientConn
}

func NewVersionServiceClient(cc *grpc.ClientConn) VersionServiceClient {
	return &versionServiceClient{cc}
}

func (c *versionServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/stakepoolrpc.VersionService/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionServiceServer is the server API for VersionService service.
type VersionServiceServer interface {
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
}

// UnimplementedVersionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVersionServiceServer struct {
}

func (*UnimplementedVersionServiceServer) Version(ctx context.Context, req *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}

func RegisterVersionServiceServer(s *grpc.Server, srv VersionServiceServer) {
	s.RegisterService(&_VersionService_serviceDesc, srv)
}

func _VersionService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stakepoolrpc.VersionService/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VersionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stakepoolrpc.VersionService",
	HandlerType: (*VersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _VersionService_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
